name = "enstate-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

routes = [
    { pattern = "worker.enstate.rs", custom_domain = true }
]

[build]
command = "cargo install -q worker-build && worker-build --release"
